### ISSUE TITLE
ニコニコ動画を再生しようとするとエラーが出ます

### ISSUE THREAD

**Issue by ghost** [Cosgy-Dev/JMusicBot-JP#11]
**バグを説明する**
ニコニコ動画を再生しようとすると曲が流れず、エラーが出ます

**スクリーンショット**
コンソールのスクリーンショット
![image](https://user-images.githubusercontent.com/55618394/65673835-869a2800-e086-11e9-8c2e-efe5534878e6.png)

**バージョン情報(以下の情報を記入してください):**
 - オペレーティングシステム(OS): windows 10 64bit
 - ボットバージョン: 0.2.1

**Comment by yupiteru63** [comment]
0.2.0で出ていた文字化けは起きておりません。
また、ニコニコ動画のメールアドレス、パスワードも正しいことを確認しました

**Comment by ryuuta0217** [comment]
なるほど...またなりましたか...
こちらでは再現できないんですよね...
ニコニコのアカウント的な問題なのか、環境の問題なのかはわかりませんが...
とりあえず、動画のURLをもらってもよいですか？？
あとは、他のニコニコの動画で試されたりしましたか？？

**Comment by yupiteru63** [comment]
新規アカウントを作りそちらのアカウントで再生したところ上手く再生できました。
ちなみに、今まで設定していたアカウントはプレミアム会員で新規で作成したアカウントは一般会員なのですが、その違いで再生できなかったということはありえるのでしょうか？

**Comment by ryuuta0217** [comment]
なるほど、プレミアム会員のアカウントだとダメなんですかねえ・・・
少し調査してみますね

**Comment by yupiteru63** [comment]
こちらでも確認したのですが、他のプレミアムアカウントでも再生できない不具合が出ました。
なので、プレミアムアカウントでは再生できない不具合があると思われます。
