### ISSUE TITLE
soundcloudの曲が再生できません

### ISSUE THREAD

**Issue by yupiteru63** [Cosgy-Dev/JMusicBot-JP#12]
**バグを説明する**
soundcloudの曲が再生できません。
musicbotを再ダウンロードして入れ直してみましたが、解決しませんでした。

**スクリーンショット**
コンソールのスクリーンショット
![image](https://user-images.githubusercontent.com/55618394/66711369-76dc4c80-edc5-11e9-8c84-04437c97dd79.png)

Discordのスクリーンショット
![image](https://user-images.githubusercontent.com/55618394/66711376-970c0b80-edc5-11e9-83b4-68fc8ed6ad82.png)

**バージョン情報(以下の情報を記入してください):**
 - オペレーティングシステム(OS): Windows10 64bit
 - ボットバージョン: 0.2.1

**Comment by ryuuta0217** [comment]
この問題はおそらくlavaplayer(オーディオ再生ライブラリ)に起因する問題でしょう。
[ここ](https://github.com/sedmelluq/lavaplayer/issues/209)を参照

**Comment by ryuuta0217** [comment]
依存関係を最新の lavaplayer 1.3.22-pre に更新した v0.2.2 がリリースされましたが、このバージョンでも再びlavaplayer側の問題が発生しているようです → https://github.com/sedmelluq/lavaplayer/issues/231
