### ISSUE TITLE
再生状態をニックネームに表示する機能で、表示状態が2つ表示される現象

### ISSUE THREAD

**Issue by yupiteru63** [Cosgy-Dev/JMusicBot-JP#16]
再生状態をニックネームに表示する機能で、特定の操作で表示状態が2つ表示されます。

**再現する方法**
問題の再現手順:
1. 曲が止まり、⏹が表示されている状態にする
2. !stopを入力する
3.⏹⏹~とニックネームが表示される

**スクリーンショット**
曲が全部再生され、止まった状態
![image](https://user-images.githubusercontent.com/55618394/68273266-51cbb880-00a9-11ea-8f6f-358e377a7d1b.png)

!stopを入力すると
![image](https://user-images.githubusercontent.com/55618394/68273224-3365bd00-00a9-11ea-83c9-6120c7e8423f.png)

**バージョン情報(以下の情報を記入してください):**
 - オペレーティングシステム(OS): Windows10 64bit
 - ボットバージョン: 0.2.4

**Comment by ryuuta0217** [comment]
この問題は現在修正中です :+1: 💯
