### ISSUE TITLE
ニコニコ動画の一部が再生できません

### ISSUE THREAD

**Issue by silver433** [Cosgy-Dev/JMusicBot-JP#18]
ニコニコ動画の音声を使用したく導入させていただきました。
#11 を参考に新規の一般アカウントを使用した所、bot自体は稼働したのですが再生できない動画があるようです。（nm形式やチャンネル動画ではありません）
何度か再送し、botの再起動をかけても同じエラーが出ました。

2008年以前の投稿動画は殆ど弾かれたので全体的には古い動画ほど引っかかるように思えますが、
2008年12月の動画（[https://www.nicovideo.jp/watch/sm5520743](https://www.nicovideo.jp/watch/sm5520743)）が再生できる一方、
2014年9月の動画（[https://www.nicovideo.jp/watch/sm24566573](https://www.nicovideo.jp/watch/sm24566573)）が再生できなかったので一概に時期の問題ではないようです。

技術的なことはわからないのですが（ニコニコ動画の仕様とかもあると思いますし）もし対応できるようでしたらお願いします。

**バージョン情報(以下の情報を記入してください):**
 - オペレーティングシステム(OS): Win8.1 64ビット
 - ボットバージョン: 0.2.6

**追加のコンテキスト**
参考までに弾かれた動画を送信したURLそのまま記載しておきます。
何れも動画の読み込み（キューへの追加）までは成功していました。
https://nico.ms/sm8228650?ref=share_others_spweb
https://www.nicovideo.jp/watch/sm24566573
https://nico.ms/sm9024225?cp_webto=share_others_iosapp
http://nico.ms/sm2478218?cp_webto=share_others_androidapp
https://nico.ms/sm982882
https://www.nicovideo.jp/watch/sm1587618

**Comment by ryuuta0217** [comment]
現時点でのこの問題に関する情報をまとめておきます

`https://www.nicovideo.jp/watch/sm5520743` (2008年)は再生できる一方
`https://www.nicovideo.jp/watch/sm24566573` (2014年)は再生できないとのことでしたが
こちらの環境ではどちらも正常に再生することができました。

しかしながら、以下のものはご報告通り再生できませんでした:
[sm8228650](https://www.nicovideo.jp/watch/sm8228650)
[sm9024225](https://www.nicovideo.jp/watch/sm9024225)
[sm2478218](https://www.nicovideo.jp/watch/sm2478218)
[sm982882](https://www.nicovideo.jp/watch/sm982882)
[sm1587618](https://www.nicovideo.jp/watch/sm1587618)

こちらの問題に関しまして、私的考察ではありますが
おそらく[ニコニコの旧動画方式から新方式への変換](http://blog.nicovideo.jp/niconews/69409.html)が行き渡っていない動画において、起こるのではないかと思われます。
こういうものに関しましてはおそらく対応が難しい/別ツールの使用 [Offliberty](http://offliberty.io/) などを介してあげる必要があると思われます。

**Comment by silver433** [comment]
＞新方式への変換
あーやっぱりそうですかね……（生放送とかで流せないやつですよね？）
返答ありがとうございます、十分助かるのでニコニコの方待つことにしますね。
