### ISSUE TITLE
Releaseバージョン 0.2.7 以降のソースファイルをビルドすると、バージョンが 0.2.6のjarが生成される。

### ISSUE THREAD

**Issue by Ruleaba** [Cosgy-Dev/JMusicBot-JP#19]
**バグを説明する**
Releaseのバージョン 0.2.7以降のソースバージョンtar.gzをダウンロードし、ビルドを実施すると、生成物バージョンが2.6.0の物が生成される

**スクリーンショット**
![issues_picture1](https://user-images.githubusercontent.com/64359927/80307377-a9024880-8803-11ea-89fd-3cc33b9dcd21.jpg)
![issues_picture2](https://user-images.githubusercontent.com/64359927/80307384-b0295680-8803-11ea-9c57-ef24808ceecb.jpg)
![issues_picture3](https://user-images.githubusercontent.com/64359927/80307389-b6b7ce00-8803-11ea-8b13-35746608d3ce.jpg)

**バージョン情報(以下の情報を記入してください):**
 - オペレーティングシステム(OS): Ubuntu 16.04.6
 - ボットバージョン: 0.2.7.1

**Comment by kosugikun** [comment]
リリース時に配布するjarファイルを使用して起動して下さい。
