### ISSUE TITLE
ループ再生時のプレイリスト交互再生バグ

### ISSUE THREAD

**Issue by kairi-2525** [Cosgy-Dev/JMusicBot-JP#34]
全曲ループ再生時、キューに複数のプレイリストを追加すると各プレイリストから交互に再生され、1曲だけ追加すると２回に１回その曲が再生されます。(シャッフル効果なし)

例

プレイリスト追加(A,B,C)
曲追加(D)

再生順
ADBDCD〜

**Comment by kosugikun** [comment]
報告ありがとうございます。
こちらの不具合は最新バージョンで修正が完了しました。
