### ISSUE TITLE
/playコマンドなどのスラッシュコマンドのみのサポートとなりました。

### ISSUE THREAD

**Issue by KazunariShimizu** [Cosgy-Dev/JMusicBot-JP#38]
ほかのBOT　例えばPtoBotなどと競合して使用できないです。

!!や!を使えるようにしてほしいです。

**Comment by kosugikun** [comment]
スラッシュコマンドはDiscordの公式が実装した機能です。
同じコマンドが実装されていたとしてもボットを指定することが可能です。

**Comment by KazunariShimizu** [comment]
ふむふむ・・試してみます。ありがとうございます。

**Comment by KazunariShimizu** [comment]
前のコマンドも戻してくださったんですね。ありがとうございます。
