### ISSUE TITLE
config aliasesで設定したエイリアスがスラッシュコマンドに反映されない問題

### ISSUE THREAD

**Issue by Crampon68** [Cosgy-Dev/JMusicBot-JP#40]
ubuntu環境下でver0.6.7でconfig aliasesで設定したエイリアスがスラッシュコマンドに反映されません。
0.6.８ではprefixコマンドには適応されましたが、スラッシュコマンドにはやはり反映されません。

**Comment by aic-6301** [comment]
スラッシュコマンドにやったらコマンド大量になるでしょう()
しかも他のBotはエイリアスでスラッシュコマンドは登録していないと思います。
なんのためのスラッシュコマンドだろうと自分は思いました
(失礼しました)
|彡ｻｯ

**Comment by kosugikun** [comment]
スラッシュコマンドにはエイリアスを設定する機能は無いためこのIssuesは閉じさせて頂きます。
これはDiscordの仕様になりますのでご理解のほどをお願いいたします。
