### ISSUE TITLE
/helpを入力時、スラッシュコマンドのhelpではなくprefixコマンドのhelpが表示される問題

### ISSUE THREAD

**Issue by Crampon68** [Cosgy-Dev/JMusicBot-JP#41]
表題の通り。ubuntu環境でver0.6.8実行時に発生。

**Comment by kosugikun** [comment]
現在、テキストコマンド・スタッシュコマンドでhelpコマンドを実行すると全てスラッシュコマンドのヘルプが表示されるように変更しましたためこのアイシューは閉じさせていただきます。
