### ISSUE TITLE
フェアキュー機能の無効化について

### ISSUE THREAD

**Issue by hvc101** [Cosgy-Dev/JMusicBot-JP#50]
複数人が曲をリクエストする際にリクエストの少ない人のリクエストが優先されるという仕様があると思うのですが、そうではなく誰がリクエストしてもリクエストされた順番に再生したいのですが、切り替え機能もしくはこのようにコード改変することは可能でしょうか？
よろしくお願いいたします。

**Comment by kosugikun** [comment]
ご意見ありがとうございます。
サーバー毎に設定できるようにするか検討してしたいと思います。

**Comment by kosugikun** [comment]
機能実装致しましたので閉じさせていただきます。
