### ISSUE TITLE
独自機能追加について

### ISSUE THREAD

**Issue by hvc101** [Cosgy-Dev/JMusicBot-JP#51]
お答えいただけるかはわからないのですが、プログラミング初心者で簡単な独自に機能追加しようとしています・
List<SlashCommand> slashCommandList = new ArrayList<>() 内部にadd(new NewCmd(bot));でコマンド登録し、コードの中身を記述し/コマンド一覧に追加したものが表示されるようになりました。
しかしいざ追加したコマンドを実行しようとすると、アプリケーションの返答がなく正しく動作しません。
正確には、コンストラクタ内のthis.bot = bot;及び this.jda = bot.getJDA();がインスタンス化の際になぜか実行自体がされておらず、以降jda型を呼び出そうとすると、Nullとなり応答なしとなってしまうようです。
まだ他コードに追加するべき内容がある、もしくはコンストラクタ自体の仕様が通常と異なるなどありましたら教えていただけないでしょうか？
お忙しいところ恐縮ですが、ご検討のほどよろしくお願いします。

**Comment by kosugikun** [comment]
コンストラクタでgetJDAを実行してもその中身はからのためNullが出力されます。
JDAのインスタンス生成はコマンドの登録をした後に実行されます。
なのでコマンド実行時にJDAのインスタンスを取得したい場合は`CommandEvent`,`SlashCommandEvent`の中にgetJDA()メゾットがあるのでそこから取得してください。

**Comment by hvc101** [comment]
ご丁寧にありがとうございます！
無事に実装できました！！
またもし何かわからないことありましたら、お問い合わせしてしまうかもしれませんが、お手隙の際にご教示頂けましたら幸いです。
