### ISSUE TITLE
ニコニコ動画を再生しようとするとエラーが出ます

### ISSUE THREAD

**Issue by yupiteru63** [Cosgy-Dev/JMusicBot-JP#8]
**バグを説明する**
ニコニコ動画を再生しようとするとコンソールにエラーメッセージが表示され、discordの方では曲が再生されません。

**スクリーンショット**
コンソールのエラーメッセージです
![image](https://user-images.githubusercontent.com/55618394/65370516-91267d00-dc94-11e9-9f26-20326323c4ce.png)

discordの方ではこうなっております
![image](https://user-images.githubusercontent.com/55618394/65370524-a9969780-dc94-11e9-9fba-af3f66ae6b29.png)

**バージョン情報(以下の情報を記入してください):**
Windows10 64bit
ボットのバージョンはバージョン0.2.0

**Comment by kosugikun** [comment]
設定ファイルの中のニコニコ動画へログインするためのユーザー名とパスワードが正しいか確認してみて下さい。

**Comment by yupiteru63** [comment]
ユーザー名とパスワードが正しいことを確認して再度起動しましたが、同じメッセージが出ました。

**Comment by ryuuta0217** [comment]
#9
