### ISSUE TITLE
[バグレポート] 設定ファイルの文字化け

### ISSUE THREAD

**Issue by ryuuta0217** [Cosgy-Dev/JMusicBot-JP#9]
**バグを説明する**
自動生成される設定ファイルは、Windows環境での実行時に文字化けを引き起こします。

**再現する方法**
問題の再現手順:
1. JMusicBot-0.2.0.jar を実行
2. 初期設定などをする
3. config.txt を確認する(コンソール画面で既に文字化けがある)

**予想される動作**
ニコニコ動画のログイン情報が間違ってプログラムに通達され、再生ができなくなる。
初回起動時を除き、毎回config.txtを削除しなければ起動不可。

**スクリーンショット**
なし

**バージョン情報(以下の情報を記入してください):**
 - Windows Any Any bit
 - 0.2.0

**追加のコンテキスト**
この問題に関する他の文脈をここに追加してください。

**Comment by yupiteru63** [comment]
ありがとうございます。
今の所解決方法はないのでしょうか？

**Comment by ryuuta0217** [comment]
コマンドライン上から
`java -Dfile.encoding=UTF-8 -jar JMusicBot-0.2.0.jar`
を実行すれば今のところ一応問題は解決しますが、現実的ではありませんね...
